apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mtls-inter-node-nodes-tls
spec:
  secretName: mtls-inter-node-nodes-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - RabbitMQ
  commonName: mtls-inter-node
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - mtls-inter-node-server-0.mtls-inter-node-nodes.default
  - mtls-inter-node-server-1.mtls-inter-node-nodes.default
  - mtls-inter-node-server-2.mtls-inter-node-nodes.default
  issuerRef:
    name: rabbitmq-ca
    kind: Issuer
    group: cert-manager.io